FROM node16.13.1-alpine

WORKDIR /src
COPY package*.json ./
COPY tsconfig.json ./
RUN yarn build
COPY ./app-react ./app-react
RUN yarn start build

FROM node:16.13.1-alpine

WORKDIR /src
COPY package*.json ./
RUN yarn install
COPY --from=0 /src/App ./App
EXPOSE 3000
CMD yarn start